apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: microservice1
        image: sayanalokesh/microservice1:latest # v.1.0
        ports:
        - containerPort: 3000
        # - targetPort: 3000
        # - port: 3000
      - name: microservice2
        image: sayanalokesh/microservice2:latest
        ports:
        - containerPort: 3001
      - name: microservice3
        image: sayanalokesh/microservice3:latest
        ports:
        - containerPort: 3002                
      - name: microservice4
        image: sayanalokesh/microservice4:latest
        ports:
        - containerPort: 3003
        # - targetPort: 3002
        # - port: 3002
  replicas: 4

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer